const $=id=>document.getElementById(id);let current=null;let detail=null;let activeTab='overview';
const tabNames={overview:'运行总览',decisions:'决策账本',evidence:'验证证据',versions:'版本与回滚',activity:'活动日志',create:'新建任务'};
const statusNames={RUNNING:'运行中',UNCERTAIN:'结果不确定',PAUSED:'已暂停',WAITING_HITL:'等待人工',COMPLETED:'已完成',FAILED:'失败'};
async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await response.json();if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
function notice(text){const el=$('notice');el.textContent=text;el.style.display='block';clearTimeout(notice.timer);notice.timer=setTimeout(()=>el.style.display='none',5000)}
function setTab(name){activeTab=name;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));$('welcome').hidden=true;$('workspace').hidden=name==='create'||!detail;$('page-title').textContent=tabNames[name];$('breadcrumb').textContent=`控制台 / ${tabNames[name]}`}
function node(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el}
function entry(title,subtitle,body){const el=node('article','entry');const head=node('div','entry-head');head.append(node('h4','',title),node('small','',subtitle||''));el.append(head);if(body){const pre=node('pre','',typeof body==='string'?body:JSON.stringify(body,null,2));el.append(pre)}return el}
function metric(label,value){const el=node('div','metric');el.append(node('span','',label),node('strong','',String(value)));return el}
function statusClass(status){return String(status||'neutral').toLowerCase()}
function repoOf(workflow){return workflow.acceptance.source_workspace||workflow.acceptance.workspace||'未关联仓库'}function basename(path){const parts=String(path).split('/').filter(Boolean);return parts.at(-1)||path}
async function loadList(select=current){const data=await api('/workflows');const list=$('workflow-list');list.replaceChildren();const groups=new Map();for(const w of data.workflows){const repo=repoOf(w);if(!groups.has(repo))groups.set(repo,[]);groups.get(repo).push(w)}for(const [repo,items]of groups){const group=node('section','repo-group');group.append(node('div','repo-name',`▾ ${basename(repo)}`),node('div','repo-path',repo));for(const w of items){const button=node('button',`workflow-item ${w.id===select?'active':''}`);button.append(node('b','',w.id),node('small','',`${statusNames[w.status]||w.status} · 第 ${w.attempt} 次`));button.onclick=()=>loadDetail(w.id);group.append(button)}list.append(group)}if(select&&data.workflows.some(x=>x.id===select))await loadDetail(select,false)}
async function sendAction(action,payload={}){if(!current)return;await api(`/workflows/${current}/${action}`,{method:'POST',body:JSON.stringify(payload)});notice('操作已提交');await loadDetail(current)}
function renderOverview(data){const w=data.workflow;const metrics=$('metrics');metrics.replaceChildren(metric('当前状态',statusNames[w.status]||w.status),metric('执行次数',`${w.attempt} / ${w.max_attempts}`),metric('决策记录',data.decisions.length),metric('当前版本',w.active_version?'已登记':'无'));
 const graph=$('graph');graph.replaceChildren();const order=[['AGENT_EXECUTE','Agent 执行'],['VERIFY','独立验证'],['VERSION_PROMOTE','版本晋级'],['WAIT_HITL','人工审批'],['COMPLETED','完成'],['FAILED','失败']];for(const [id,label]of order){const el=node('div',`node ${w.current_node===id?'current':''}`,label);el.title=id;graph.append(el)}
 const contract=$('contract');contract.replaceChildren(node('p','contract-goal',w.goal));const chips=node('div','chips');if(w.acceptance.source_workspace)chips.append(node('span','chip',`源仓库: ${w.acceptance.source_workspace}`));if(w.acceptance.workspace)chips.append(node('span','chip',`运行 worktree: ${w.acceptance.workspace}`));for(const command of w.acceptance.commands||[])chips.append(node('span','chip',`验证: ${command}`));for(const file of w.acceptance.allowed_files||[])chips.append(node('span','chip',`范围: ${file}`));contract.append(chips);
 const latest=$('latest-decisions');latest.replaceChildren(...data.decisions.slice(-3).reverse().map(x=>entry(`${x.decision_type} · ${x.decision}`,x.question,{理由:x.rationale,风险:x.risk})));
 const actions=$('workflow-actions');actions.replaceChildren();const byStatus={RUNNING:[['暂停','pause',{},'']],PAUSED:[['恢复','resume',{},'']],WAITING_HITL:[['批准','hitl',{decision:'approve'},'approve'],['重试','hitl',{decision:'retry'},''],['拒绝','hitl',{decision:'reject'},'']]};for(const item of byStatus[w.status]||[]){const b=node('button',item[3],item[0]);b.onclick=()=>sendAction(item[1],item[2]).catch(e=>notice(e.message));actions.append(b)}}
function renderHitl(data){const banner=$('hitl-banner');const open=data.hitl.slice().reverse().find(x=>!x.resolved_at);if(data.workflow.status!=='WAITING_HITL'||!open){banner.hidden=true;return}banner.hidden=false;const labels={promotion_review:'自动验证已通过，等待你审核 diff 和证据后决定是否创建 Git 版本。',max_attempts_reached:'自动尝试次数已耗尽，需要你决定重试或终止。'};$('hitl-reason').textContent=labels[open.reason]||`暂停原因：${open.reason}。请检查验证证据与决策账本。`;$('hitl-approve').onclick=()=>sendAction('hitl',{decision:'approve'}).catch(e=>notice(e.message));$('hitl-retry').onclick=()=>sendAction('hitl',{decision:'retry'}).catch(e=>notice(e.message));$('hitl-reject').onclick=()=>sendAction('hitl',{decision:'reject'}).catch(e=>notice(e.message))}
function renderRecovery(data){const banner=$('recovery-banner');if(data.workflow.status!=='UNCERTAIN'){banner.hidden=true;return}banner.hidden=false;const recover=action=>sendAction('recover',{action}).catch(e=>notice(e.message));$('recover-verify').onclick=()=>recover('verify-existing');$('recover-retry').onclick=()=>recover('retry-same-attempt');$('recover-restore').onclick=()=>recover('restore-baseline');$('recover-abort').onclick=()=>recover('abort-preserve')}
function renderDecisions(data){$('decisions').replaceChildren(...data.decisions.slice().reverse().map(x=>entry(`${x.decision_type} / ${x.decision}`,x.question,{理由:x.rationale,证据:x.evidence,备选:x.alternatives,风险:x.risk,预期:x.expected_effect,时间:x.created_at})))}
function renderEvidence(data){const passed=data.verifications.filter(x=>x.passed).length;const failed=data.verifications.length-passed;$('evidence-summary').replaceChildren(metric('验证轮次',data.verifications.length),metric('通过',passed),metric('失败',failed));const cards=data.verifications.slice().reverse().map(x=>{const el=node('article',`evidence-card ${x.passed?'pass':'fail'}`);el.append(node('h3','',x.passed?'验证通过':'验证失败'),node('p','',`第 ${x.attempt} 次 · ${x.feedback}`),node('pre','',JSON.stringify(x.evidence,null,2)));return el});$('evidence').replaceChildren(...cards)}
function renderVersions(data){const active=data.workflow.active_version;const cards=data.versions.slice().reverse().map(x=>{const el=node('article',`version-card ${x.id===active?'active':''}`);el.append(node('div','version-dot',x.status==='BASELINE'?'BASE':x.status==='PROMOTED'?'LIVE':'ROLL'));const body=node('div');body.append(node('h3','',x.id),node('p','',`状态：${x.status} · 父版本：${x.parent_id||'无'}`),node('pre','',JSON.stringify(x.artifact,null,2)));el.append(body);if(x.id!==active){const b=node('button','', '回滚到此版本');b.onclick=()=>sendAction('rollback',{version_id:x.id}).catch(e=>notice(e.message));el.append(b)}return el});$('versions').replaceChildren(...cards)}
function renderActivity(data){$('activity').replaceChildren(...data.events.slice().reverse().map(x=>{const el=node('article','activity-item');el.append(node('strong','',x.type),node('small','',`${x.from_node||'START'} → ${x.to_node||'-'} · ${x.created_at}`));if(Object.keys(x.payload||{}).length)el.append(node('pre','',JSON.stringify(x.payload,null,2)));return el}))}
async function loadDetail(id,updateList=true){current=id;detail=await api(`/workflows/${id}`);const w=detail.workflow;$('status').textContent=statusNames[w.status]||w.status;$('status').className=`status ${statusClass(w.status)}`;renderHitl(detail);renderRecovery(detail);renderOverview(detail);renderDecisions(detail);renderEvidence(detail);renderVersions(detail);renderActivity(detail);$('welcome').hidden=true;$('workspace').hidden=activeTab==='create';if(updateList)await loadList(id)}
document.querySelectorAll('.nav-item').forEach(button=>button.onclick=()=>setTab(button.dataset.tab));document.querySelectorAll('[data-open-create]').forEach(button=>button.onclick=()=>setTab('create'));$('refresh').onclick=$('top-refresh').onclick=()=>loadList(current).catch(e=>notice(e.message));
$('create-form').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget;const submit=form.querySelector('button[type="submit"]');if(submit.disabled)return;submit.disabled=true;submit.textContent='运行中…';const f=new FormData(form);const payload={id:f.get('id'),goal:f.get('goal'),max_attempts:Number(f.get('maxAttempts')),acceptance:{workspace:f.get('workspace'),commands:[f.get('command')],allowed_files:String(f.get('allowed')).split(',').map(x=>x.trim()).filter(Boolean),require_promotion_approval:true}};notice('正在创建 worktree 并运行 DSH，请稍候…');try{await api('/workflows',{method:'POST',body:JSON.stringify(payload)});form.reset();activeTab='overview';await loadDetail(payload.id);setTab('overview')}catch(e){notice(e.message)}finally{submit.disabled=false;submit.textContent='启动工作流'}};
loadList().then(()=>{if(!current){$('welcome').hidden=false;$('workspace').hidden=true}}).catch(e=>notice(e.message));
